### ISSUE TITLE
Zip-lookup does not return the default city name

### ISSUE THREAD

**Issue by fitzgerald** [Protricity/zip-lookup#1]
The city names that are returned from the lookup are not the default, recognized name.

For example, using 15222 in your database maps to  'Downtown'. 
The usps prefers the default name 'Pittsburgh'. 

Here is an example:
https://tools.usps.com/go/ZipLookupResultsAction!input.action?resultMode=2&companyName=&address1=&address2=&city=&state=Select&urbanCode=&postalCode=15222&zip=

**Comment by Protricity** [comment]
Hey there, thanks for the feedback. Basically this discrepancy will occur when the database falls out of date from actual data. For this reason I've included my php script to update the zip cache with a sql db (and re-write each cache file). If this is done (or if a manual fix is preferred), a push can be made to the repo to update (for everyone else) to fix the discrepancy. 
I'm happy to offer access for anyone who wants to refresh the db (or create look ups for other countries). Eventually I'll revisit the project and go a different direction; something that doesn't have to be periodically updated, preferably. 
If you need any help (or repo access), or if you can make the case that the current db is significantly out of date then let me know and I'll hop back on

**Comment by fitzgerald** [comment]
Hi,

Thanks for following up. I think the issue isn’t because the data falls out of date; I think it happens because there can be multiple, valid city names for a given zip code. The example I sent (15222) can be Downtown, Pgh or Pittsburgh. Pittsburgh would be the default (or preferred) name.

I have a feeling when you culled the  original data, you probably grabbed the first city name alphabetically instead of the default.

I have table locally with default city names that I can use to update the sql db in your repo. Unfortunately, my table doesn’t have the lat/long columns, so I can’t update those.  Would you still want a pull request without the latitude/longitude columns? I don’t think you are using them, but you might have plans for them in the future.

Thanks,
Patrick

**Comment by Protricity** [comment]
Gotcha. I'll review the code today and get back to you on this. 
Thanks for the report

**Comment by Protricity** [comment]
Alright, looks like the db does indeed have multiple valid options for a single zipcode. I'm thinking this means we have no use for the duplicates and need to simply the db into one-to-one. 
I don't see an easy way to get the 'default' city, so maybe we should look at a better zip db than I've found so far. 
Will keep you updated

**Comment by fitzgerald** [comment]
Thanks! Again, if you need a table of default cities, I have one.

**Comment by Protricity** [comment]
So I re-wrote the db script in node.js and refactored the files down a directory for cleanliness. The script pulls the latest (2012) from 
http://federalgovernmentzipcodes.us/
and process the data directly into the cache files (no sqlite db needed).
If you don't mind seeing if this new db fits your project better. Just pull the latest head. 
Note: New script location

This update also solves zipcodes that do not show up correctly due to being 0XXXX. There was a few bug reports on googlecode I had not noticed until now that should be solved (Google kinda messed things up by pulling the plug).

Hope this helps,
-Ari

**Comment by fitzgerald** [comment]
Awesome! Thanks for taking care of this. You've made my day!

**Comment by Protricity** [comment]
Your welcome. New demo is up at
http://protricity.github.io/zip-lookup/
